name: My first workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main
  # schedule:
    # - cron: '0 5 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Use node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Print a message
      run: echo "Hello, pmt"

    - name: Run custom action
      uses: tuepmtcloud/greeting-action@main 